app: serverless-ecommerce
service: serverless-ecommerce
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  getUsers:
    handler: src/serverless/functions/user/getUsers.handler
    events:
      - httpApi:
          path: /users
          method: get
  createUser:
    handler: src/serverless/functions/user/registerUser.handler
    events:
      - httpApi:
          path: /users
          method: post
  getUserById:
    handler: src/serverless/functions/user/getUserById.handler
    events:
      - httpApi:
          path: /users/{userId}
          method: get
  deleteUser:
    handler: src/serverless/functions/user/deleteUser.handler
    events:
      - httpApi:
          path: /users/{userId}
          method: delete
  updateUser:
    handler: src/serverless/functions/user/updateUser.handler
    events:
      - httpApi:
          path: /users/{userId}
          method: put
  createOrder:
    handler: src/serverless/functions/store/order/createOrder.handler
    events:
      - httpApi:
          path: /orders
          method: post
  deleteOrder:
    handler: src/serverless/functions/store/order/deleteOrder.handler
    events:
      - httpApi:
          path: /orders/{orderId}
          method: delete
  getOrders:
    handler: src/serverless/functions/store/order/getOrders.handler
    events:
      - httpApi:
          path: /orders
          method: get
  getOrdersByUser:
    handler: src/serverless/functions/store/order/getOrdersByUser.handler
    events:
      - httpApi:
          path: /orders/{userId}
          method: get
  updateOrder:
    handler: src/serverless/functions/store/order/updateOrder.handler
    events:
      - httpApi:
          path: /orders/{orderId}
          method: put
  createProduct:
    handler: src/serverless/functions/store/product/createProduct.handler
    events:
      - httpApi:
          path: /products
          method: post
  deleteProduct:
    handler: src/serverless/functions/store/product/deleteProduct.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: delete
  getProducts:
    handler: src/serverless/functions/store/product/getProducts.handler
    events:
      - httpApi:
          path: /products
          method: get
  getProductById:
    handler: src/serverless/functions/store/product/getProductById.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: get
  updateProduct:
    handler: src/serverless/functions/store/product/updateProduct.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: put

plugins:
  - serverless-offline
  - serverless-plugin-typescript